name: Build and Publish to GH Packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: |
        sha=${GITHUB_SHA:0:7}
        app="${GITHUB_REPOSITORY#*/}"
        docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha .
    - name: Push the image to GPR
      run: |
        sha=${GITHUB_SHA:0:7}
        app="${GITHUB_REPOSITORY#*/}"
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha
